### ISSUE TITLE
Dangerous inclusion of real username/password/domain

### ISSUE THREAD

**Issue by matthewheck** [kellymears/xtra#2]
https://github.com/kellymears/xtra/blob/e7fec0c1f029d8b4374c8d6712e1047194012e51/models/index.js#L2

Even if you have no intention of using this longer term, somebody with nefarious aims may take advantage of this being here and use it inappropriately. I'd highly recommend you close down that particular account and extract the information into a gitignored settings/config file.

The file can be as simple as `config.js` with an exported module that contains key-value pairs for important data.

**Comment by kellymears** [comment]
It definitely is for dev only. In production I think I'd want to host my own db on a separate instance, or using a different provider. I will figure out how to extract this however.

**Comment by kellymears** [comment]
This is now resolved.
